### ISSUE TITLE
Output Hydra config from napari

### ISSUE THREAD

**Issue by berombau** [saeyslab/napari-sparrow#83]
It would be nice for user in napari to tweak parameters in the napari widgets and in the end have a button to export the tweaks to a Hydra config, to enable running the whole sample or multiple samples with the parameters.

- [x] get current config options of all steps in all widgets in napari
- [x] get current default config (Hydra compose function and resolve the config)
- [x] create dicts of both configs with similar keys
- [ ] find differences (omegaconf does not seem to support this, try something like [deepdiff](https://github.com/seperman/deepdiff))
- [ ] write out differences in yaml as dataset config

Example output `default.yaml`, to be placed in the local folder `/configs/experiment/`:
```yaml
# @package _global_

# These options inherit from other configs and should be always on top
defaults:
  - override /segmentation: cellpose

# TODO: These options are better suited in an extra config at `configs/local/default.yaml` 
paths:
  data_dir: FILL_IN_YOUR_DATA_FOLDER_PATH
device: "cpu"

# TODO: These options are better suited in an extra config at `configs/dataset/type_name.yaml` 
dataset:
  data_dir: ${paths.data_dir}/resolve_liver
  dtype: tiff
  image: ${dataset.data_dir}/20272_slide1_A1-1_DAPI.tiff
  coords: ${dataset.data_dir}/20272_slide1_A1-1_results.txt
  markers: ${dataset.data_dir}/markerGeneListMartinNoLow.csv

# The combination of these options should be unique to this experiment
segmentation:
  min_size: 100
```

Check if config is correct:
```
spongepy --cfg job
```

Experiment config will automatically be picked up. If the user is more advanced, they can restructure the config in `dataset`, `local` and multiple `experiment` configs.
